### ISSUE TITLE
Loader_entrypoint needs exposing and extra LoaderCoreFunction initialize() for Swift

### ISSUE THREAD

**Issue by mattcolegate** [RuntimeTools/omr-agentcore#4]
During the development of the Agent loader for Swift, the following came to light:
- There seemed to be no reason not to expose loader_entrypoint() in AgentExtensions.h and it would be helpful if it was available
- Swift specifies init() as a keyword, so I was unable to call that LoaderCoreFunction. A further initialize() function should be made available and point to the same thing that init() does.

**Comment by mattcolegate** [comment]
Created pull request #5 for this issue

**Comment by tobespc** [comment]
@mattcolegate  is this still required with the change I just accepted ?

**Comment by mattcolegate** [comment]
No, the change fixes this issue, so I will close.
