### ISSUE TITLE
IBM Confidential material in strUtils.h and .cpp

### ISSUE THREAD

**Issue by davidjmccann** [RuntimeTools/omr-agentcore#66]
This should be open source?
/**
 * IBM Confidential
 * OCO Source Materials
 * IBM Monitoring and Diagnostic Tools - Health Center
 * (C) Copyright IBM Corp. 2007, 2015 All Rights Reserved.
 * The source code for this program is not published or otherwise
 * divested of its trade secrets, irrespective of what has
 * been deposited with the U.S. Copyright Office.
 */

**Comment by tobespc** [comment]
looks like we have an incorrect header statement

**Comment by mattcolegate** [comment]
Change has been merged - please re-open the issue if there is still a problem.
