### ISSUE TITLE
Allow for IBM i PASE Support

### ISSUE THREAD

**Issue by abmusse** [RuntimeTools/omr-agentcore#68]
While working on getting appmetrics (uses omr-agentcore as a sub-module) installed on PASE, I ran into problems compiling on IBM i. I had to include some if defined checks for PASE and some different implementation when on PASE. Since PASE uses an AIX-like environment some paths were identical, while at times the two diverged. I am working on PR that would allow for PASE support , and plan submit next week.

**Comment by abmusse** [comment]
Update PR is now open https://github.com/RuntimeTools/omr-agentcore/pull/69

**Comment by mattcolegate** [comment]
@abmusse Change has been merged - can you please retest and close this issue if it has been resolved?
