### ISSUE TITLE
Remove test file which contains legal issue

### ISSUE THREAD

**Issue by NikCanvin** [RuntimeTools/omr-agentcore#85]
Please remove the following, as it contains an Error in it's copyright text (as confirmed by the Paho team, they are also removing this file from the base project and re-spinning a release this week):

https://github.com/RuntimeTools/omr-agentcore/blob/master/org.eclipse.paho.mqtt.c/test/MQTTTest_v2.c

**Comment by mattcolegate** [comment]
Completed by @stalleyj in https://github.com/RuntimeTools/omr-agentcore/pull/86
