### ISSUE TITLE
com.ibm.diagnostics.healthcenter.plugins WARNING: [cpu_os] At least one data gathering failure occurred

### ISSUE THREAD

**Issue by jhondavila** [RuntimeTools/omr-agentcore#9]
Tengo el siguiente error en appmetrics:

com.ibm.diagnostics.healthcenter.plugins WARNING: [cpu_os] At least one data gathering failure occurred

SO : WIN7 X64
NodeJs : v6
alguna ayuda por favor.

**Comment by tobespc** [comment]
@jhondavila  Could you restest with the latest version of appmetrics from npmjs.org please as we added a change

**Comment by tobespc** [comment]
@jhondavila can you let me know if this is still an issue as otherwise we will close this off. Thanks

**Comment by arnoldss** [comment]
I have this issue btw also

**Comment by arnoldss** [comment]
environment.npm_config_user_agent:npm/3.10.9 node/v6.5.0 win32 x64 windows 10

**Comment by arnoldss** [comment]
"appmetrics": "^1.2.0",

**Comment by tobespc** [comment]
We are not seeing this with the latest version.  Please reopen if you are getting it on 3.0.x of appmetrics
